### ISSUE TITLE
bmx6 r2015061604-4 with no sms_plugin crashes when trying to mesh with another bmx6 *with* sms plugin enabled

### ISSUE THREAD

**Issue by altergui** [bmx-routing/bmx6#7]
hey axel!
we justed bumped into this bug:

on a mesh network made of around ~60 bmx6 nodes with sms_plugin enabled, trying to add one node with bmx6 but _no_ sms_plugin enabled, makes that node crash with the following error

Wed Feb 24 09:24:07 2016 daemon.err bmx6[3792]: ERROR ip_flush_rules(): removed orphan IPv4 rule to table 60
Wed Feb 24 09:24:07 2016 daemon.err bmx6[3792]: ERROR ip_flush_rules(): removed orphan IPv6 rule to table 60
Wed Feb 24 09:24:07 2016 daemon.err bmx6[3792]: WARN  dev_check(): detected valid but disabled dev=wlan1-adhoc_12 ! Activating now...
Wed Feb 24 09:24:07 2016 daemon.err bmx6[3792]: WARN  dev_activate(): dev=wlan1-adhoc_12
Wed Feb 24 09:24:07 2016 daemon.err bmx6[3792]: INFO  dev_reconfigure_soft(): enabled wireless umin=6222K umax=56000K umax=56000000 umax_conf=18446744073709551615 undef=18446744073709551615 dev=wlan1-adhoc_12 MAC: 6470023E9D2A link-local fe80::6670:2ff:fe3e:9d2a/64 global fd66:66:66:10:6670:2ff:fe3e:9d2a/64 brc ff02::2
Wed Feb 24 09:24:07 2016 daemon.err bmx6[3792]: INFO  check_proc_sys_net(): changing /proc/sys/net/ipv4/conf/bmxtmain/accept_local from 0 to 1
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: WARN  rx_frame_iterate(): process_description_tlvs - unknown type=16 ! check for updates
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR First SIGSEGV -501358 received, try cleaning up...
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 rx_frame_iterate()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 process_description_tlv_hna()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 ip_netmask_validate()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 is_ip_valid()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 ip_netmask_validate()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 ip_netmask_validate()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 ip_netmask_validate()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 is_ip_valid()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 ip_netmask_validate()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 ip_netmask_validate()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 ip_netmask_validate()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 is_ip_valid()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 is_ip_valid()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 ip_netmask_validate()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 ip_netmask_validate()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 rx_frame_iterate()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 process_description_tlv_tun6_adv()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 is_ip_valid()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 ip_netmask_validate()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 ip_netmask_validate()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 rx_frame_iterate()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 process_description_tlv_tunXin6_net_adv()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 ip_netmask_validate()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 rx_frame_iterate()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 process_description_tlv_tunXin6_net_adv()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 ip_netmask_validate()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 process_description_tlvs()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 rx_frame_iterate()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 process_description_tlv_metricalgo()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 metricalgo_tlv_to_host()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 fmetric_to_umetric()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 validate_metricalgo()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 fmetric_to_umetric()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 _add_tun_bit_node()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 eval_tun_bit_tree()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 task_remove()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 _recalc_tun_bit_tree()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 rx_frame_iterate()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 cleanup_all()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR debug_function_calls():       3070 segmentation_fault()
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR Terminating with error code -501358 (BMX6-0.1-alpha-rev8f26909e8808ed7fab0359afc15a3e44563fbd40)! Please notify a developer
Wed Feb 24 09:24:10 2016 daemon.err bmx6[3792]: ERROR Second SIGSEGV -500234 received, giving up! core contains second SIGSEV!

simply enabling sms_plugin like this:

root@3e9d28:/etc/config# bmx6 -cp
 plugin                 bmx6_sms.so  
 plugin                 bmx6_config.so  
 plugin                 bmx6_json.so  
 ipVersion              6  
 dev                    wlan1-adhoc_12  
    /linklayer          2  
 tunDev                 tmain  
    /tun4Address        10.1.29.1/28  
    /tun6Address        2012:0:1:c171::1/64  
 syncSms                chat                 

makes the new node work properly

but without the "plugin=bmx6_json.so" it crashes as mentioned, and we believe this should not happen

sincerely,
pau, gio, rogerpueyo, and gui :)

**Comment by axn** [comment]
Hi,

I think this bug got fixed with d8221d6ba6eb55339122f735bfa416f41fbc4ee5
can you try with latest bmx6/master-branch version?

/axel

**Comment by axn** [comment]
Checked also openwrt-routing packages in master and for-15.05 branches and both pull a more recent version already. Please close issue if it works for you /axel

**Comment by axn** [comment]
This bug is indeed fixed. With 0312168aaa384379ccbefd4b2d936fc698664d5b the corresponding warning message indicating to look out for updates or plugins are also muted
